# Generated by Django 4.0.5 on 2022-06-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Cliente')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre Cliente')),
                ('nombreUsuario', models.CharField(max_length=20, verbose_name='Nombre Usuario')),
                ('correo', models.CharField(max_length=20, verbose_name='Correo Cliente')),
                ('contraseña', models.CharField(max_length=8, verbose_name='contraseña1')),
                ('scontraseña', models.CharField(max_length=8, verbose_name='contraseña2')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nombreProducto', models.CharField(max_length=20, verbose_name='Nombre Del Producto')),
                ('tipoProducto', models.CharField(max_length=20, verbose_name='Tipo de producto')),
                ('fotoProducto', models.ImageField(upload_to='producto')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Descripcion')),
            ],
        ),
    ]
